### ISSUE TITLE
How To Deploy Cpanel

### ISSUE THREAD

**Issue by mrzonk** [xirf/xirf-portofolio#15]
ini khusus buat dideploy ke vercel saja ya?

**Comment by xirf** [comment]
Hi, 
Untuk deploy di CPanel silahkan ubah output dan adapter di astro.config.mjs menjadi seperti ini

```js
  output: "static",
  // adapter: vercel(), // Dihapus karena akan dijadikan static file
```

setelah itu salin semua file di dalam folder `dist` ke dalam `public_html` atau folder domain root lain di CPanel.

Jika ingin menambahkan fungsi lain yang membutuhkan SSR kamu bisa mengikuti guide [di dokumentasi @astrojs/node](https://docs.astro.build/en/guides/integrations-guide/node/)

<hr />

To deploy on CPanel, please modify the output and adapter in `astro.config.mjs` to be like this:

```js
  output: "static",
  // adapter: vercel(), // Removed as it will be converted to static files
```

After that, copy all files from the `dist` folder to the `public_html` or another domain root folder in CPanel.

If you need to add other functions that require SSR, you can follow the guide [in the @astrojs/node documentation](https://docs.astro.build/en/guides/integrations-guide/node/).
